name = "formrecap-classify"
main = "src/index.ts"
compatibility_date = "2026-04-01"
workers_dev = true

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "STATE"
id = "fad219967723417f9e014b91c3a734e2"
